FROM nginx:alpine

COPY proxy.conf /etc/nginx/proxy.conf
COPY uploadsize.conf /etc/nginx/conf.d/uploadsize.conf
COPY proxy-hub.conf /etc/nginx/conf.d/proxy-hub.conf
COPY data.ensg-sdi.docker.conf /etc/nginx/conf.d/data.ensg-sdi.docker.conf